// Generated by CoffeeScript 1.9.2
(function() {
  var BaseCtrl, utils;

  utils = require('../utils');

  BaseCtrl = (function() {
    function BaseCtrl() {}

    BaseCtrl.prototype.params = {
      getId: function(req, res, next, id) {
        return utils.buildObjectID(id, function(err, result) {
          if (err) {
            return next(err);
          }
          console.log("id:", result);
          req.params.id = result;
          return next();
        });
      }
    };

    BaseCtrl.prototype.create = function(req, res, next) {
      return this.model.save(req.body, function(err, result) {
        if (err) {
          return next(err);
        }
        return res.json(result);
      });
    };

    BaseCtrl.prototype.update = function(req, res, next) {
      var entity, id;
      id = req.params.id;
      entity = req.body;
      entity.id = id;
      return this.model.update(entity, function(err, result) {
        if (err) {
          return next(err);
        }
        return res.json(result);
      });
    };

    BaseCtrl.prototype.queryById = function(req, res, next) {
      var id;
      id = req.params.id;
      return this.model.findById(id, function(err, result) {
        if (err) {
          return next(err);
        }
        return res.json(result);
      });
    };

    return BaseCtrl;

  })();

  module.exports = BaseCtrl;

}).call(this);
