// Generated by CoffeeScript 1.9.2
(function() {
  var BaseCtrl, CategoryCtrl,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseCtrl = require('./base');

  CategoryCtrl = (function(superClass) {
    extend(CategoryCtrl, superClass);

    function CategoryCtrl(models) {
      this.name = 'category';
      this.model = models.Category;
    }

    return CategoryCtrl;

  })(BaseCtrl);

  module.exports = CategoryCtrl;

}).call(this);
