// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(models) {
    return {
      ArticleCtrl: new (require('./article'))(models),
      CategoryCtrl: new (require('./category'))(models),
      TagCtrl: new (require('./tag'))(models)
    };
  };

}).call(this);
