// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(models) {
    return {
      Article: new (require('./article'))(models),
      Category: new (require('./category'))(models),
      Tag: new (require('./tag'))(models)
    };
  };

}).call(this);
