// Generated by CoffeeScript 1.9.2
(function() {
  var Article, BaseModel,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseModel = require('./base');

  Article = (function(superClass) {
    extend(Article, superClass);

    Article.rule = {
      category: {
        required: false
      },
      tags: {
        required: false
      },
      title: {
        required: true
      },
      content: {
        required: true
      },
      cover: {
        required: false
      },
      publishTime: {
        required: false
      },
      lastUpdate: {
        required: false
      }
    };

    Article.name = 'article';

    function Article(db) {
      this.collection = db.collection(this.name);
    }

    return Article;

  })(BaseModel);

  module.exports = Article;

}).call(this);
