// Generated by CoffeeScript 1.9.2
(function() {
  var BaseModel;

  BaseModel = (function() {
    function BaseModel() {}

    BaseModel.prototype.build = function(object) {
      var entity, key, options, ref;
      entity = {};
      ref = this.rule;
      for (key in ref) {
        options = ref[key];
        if (options != null) {
          if (options.required && !object[key]) {
            throw new Error(key + " must be required");
          }
        }
        entity[key] = object[key];
      }
      return entity;
    };

    BaseModel.prototype.save = function(model, callback) {
      return this.collection.insert(model, function(err, result) {
        var ref;
        return callback(err, (result != null ? (ref = result.ops) != null ? ref[0] : void 0 : void 0) || {});
      });
    };

    BaseModel.prototype.update = function(model, callback) {
      var _id;
      _id = model._id;
      delete model._id;
      return this.collection.findOneAndUpdate({
        _id: _id
      }, {
        $set: model
      }, {
        returnOriginal: false,
        upsert: false
      }, function(err, result) {
        if (err) {
          return callback(err);
        }
        return callback(null, (result != null ? result.value : void 0) || {});
      });
    };

    BaseModel.prototype.remove = function(model, callback) {
      return this.collection.remove({
        _id: model._id
      }, callback);
    };

    BaseModel.prototype.findById = function(id, callback) {
      return this.collection.findOne({
        _id: id
      }, callback);
    };

    return BaseModel;

  })();

  module.exports = BaseModel;

}).call(this);
