// Generated by CoffeeScript 1.9.2
(function() {
  var BaseModel, Category,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseModel = require('./base');

  Category = (function(superClass) {
    extend(Category, superClass);

    Category.name = 'category';

    function Category(db) {
      this.collection = db.collection(this.name);
    }

    return Category;

  })(BaseModel);

  module.exports = Category;

}).call(this);
