// Generated by CoffeeScript 1.9.2
(function() {
  var Article, Category, Tag;

  Article = require('./article');

  Category = require('./category');

  Tag = require('./tag');

  module.exports = function(db) {
    return {
      Article: new Article(db),
      Category: new Category(db),
      Tag: new Tag(db)
    };
  };

}).call(this);
