// Generated by CoffeeScript 1.9.2
(function() {
  var BaseModel, Tag,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseModel = require('./base');

  Tag = (function(superClass) {
    extend(Tag, superClass);

    function Tag(db) {
      this.collection = db.collection('tag');
      this.rule = {
        name: {
          required: true
        }
      };
    }

    return Tag;

  })(BaseModel);

  module.exports = Tag;

}).call(this);
