// Generated by CoffeeScript 1.9.2
(function() {
  var async, boxing, boxingControllers;

  async = require('async');

  boxing = function(ctrl) {
    var box, name, value;
    box = {
      model: ctrl.model,
      params: ctrl.params
    };
    for (name in ctrl) {
      value = ctrl[name];
      if (typeof value !== 'function') {
        continue;
      }
      if (name === 'constructor') {
        continue;
      }
      switch (value.length) {
        case 3:
          box[name] = (function(name) {
            return function(req, res, next) {
              console.log('%s handler:%s', ctrl.name, name);
              return ctrl[name](req, res, next);
            };
          })(name);
          break;
        case 4:
          box[name] = value;
          break;
        default:
          console.log('unknown handler: %s, args length: %d', name, value.length);
      }
    }
    return box;
  };

  boxingControllers = function(ctrls) {
    var ctrl, ctrlName, result;
    result = {};
    for (ctrlName in ctrls) {
      ctrl = ctrls[ctrlName];
      result[ctrlName] = boxing(ctrl);
    }
    return result;
  };

  module.exports = function(server, callback) {
    return async.auto({
      'db': function(done) {
        return (require('./db')).init(done);
      },
      'ctrls': [
        'db', function(done, results) {
          var ctrls, models;
          models = (require('./models'))(results.db);
          ctrls = (require('./ctrls'))(models);
          ctrls = boxingControllers(ctrls);
          return done(null, ctrls);
        }
      ],
      'route': [
        'ctrls', function(done, results) {
          var route;
          route = require('./route');
          route(server, results.ctrls);
          return done();
        }
      ]
    }, function(err, results) {
      return callback(err);
    });
  };

}).call(this);
