// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(server, ctrls) {
    server.param('tagId', ctrls.Tag.params.getId);
    server.post('/tags', ctrls.Tag.create);
    server.get('/tags/:tagId', ctrls.Tag.queryById);
    return server.post('/tags/:tagId', ctrls.Tag.update);
  };

}).call(this);
