// Generated by CoffeeScript 1.9.2
(function() {
  var async, bodyParser, cookieParser, express, init, server;

  async = require('async');

  express = require('express');

  cookieParser = require('cookie-parser');

  bodyParser = require('body-parser');

  server = express();

  server.use(bodyParser.json({}));

  server.use(bodyParser.urlencoded({
    extended: false
  }));

  server.use(cookieParser());

  init = require('./init');

  init(server, function(err) {
    var port;
    if (err) {
      return console.log(err);
    }
    port = 10080;
    return server.listen(port, function() {
      return console.log('listening at %s', 10080);
    });
  });

}).call(this);
