// Generated by CoffeeScript 1.9.2
(function() {
  var bodyParser, cookieParser, express, port, route, server;

  express = require('express');

  cookieParser = require('cookie-parser');

  bodyParser = require('body-parser');

  server = express();

  server.use(bodyParser.json({}));

  server.use(bodyParser.urlencoded({
    extended: false
  }));

  server.use(cookieParser());

  route = require('./route');

  route(server);

  port = 8003;

  server.listen(port, function() {
    return console.log('listening at %s', 8003);
  });

}).call(this);
