// Generated by CoffeeScript 1.9.2
(function() {
  var mongodb;

  mongodb = require('mongodb');

  module.exports = {
    buildObjectID: function(value, callback) {
      var err, id;
      try {
        id = new mongodb.ObjectID(value);
        return callback(null, id);
      } catch (_error) {
        err = _error;
        return callback(err);
      }
    }
  };

}).call(this);
